### ISSUE TITLE
Generate executable

### ISSUE THREAD

**Issue by bugMaker-237** [RMPR/atbswp#3]
This is a request to be able to test the tool without having to install python on my machine. I'm not a python dev. I think the tool is very interesting. I would have loved to test it but apparently I must install python to get it done. Don't know how python works but is it not possible to get the a beta release as executable ?

**Comment by RMPR** [comment]
The releases will be ready as soon as some core features are implemented, unfortunately right now you need to install Python if you want to test. I assume you're on Windows, (because if not, Python 3 is likely already installed on your platform) just download [this executable (Python 3.8)](https://www.python.org/downloads/release/python-381/), install it and you'll be ready to go, I made the installation process for the dev environment as smooth as possible.
Additionally there is a guide for you if you really need one:
[installing Python](https://realpython.com/installing-python/)

**Comment by Nivekiba** [comment]
@bugMaker-237 is your problem (about this issue) is solved ?

**Comment by thecursedfly** [comment]
Hi, may I suggest, for Linux, to create a Flatpak (https://flatpak.org/) package? That would allow us to install it easily on different distributions without the requirement of repackaging it for every newer distro release, and could provide sandboxing features. (Unfortunately I'm not a developer, so I can only suggest)

**Comment by RMPR** [comment]
Thanks for your suggestion, but packaging is not really a big issue in the case of this project, we use [poetry](https://python-poetry.org/) to manage dependencies and building for any platform supported by Python is as simple as running ```poetry build``` in the root of the repo, there are no releases now because I don't consider the project mature enough to be released, but if you want a package, now you know how to do it.

**Comment by sojusnik** [comment]
Thanks for this handy app! Would love, if we could install it via pip(3)!

**Comment by globeone** [comment]
If you need to interact low level with the OS then a Linux AppImage would be a better choice. Runs on any Linux platform without any dependancy issues.
https://appimage.org

**Comment by RMPR** [comment]
@bugMaker-237, I'm really happy to announce the v0.1 release, you can access the executables for the supported platforms [here](https://github.com/RMPR/atbswp/releases/tag/v0.1), don't hesitate to share your feedback.
