### ISSUE TITLE
Hotkeys don't work unless atbswp has focus

### ISSUE THREAD

**Issue by bmn001** [RMPR/atbswp#51]
## Checklist
- [x] I use the latest release of atbswp
- [x] The issue is not existing yet

## Verbose log

/tmp/atbswp-* doesn't seem to exist on my system

### Operating System
Ubuntu 20.10

### Desktop Environment/Window Manager
X11 / Gnome 3.38.3

### Python version
3.8.6

## Description

atbswp only responds to hotkeys when the atbswp window has focus.

Infinite Playback of a mouse click macro had gone awry and I was slamming F9 to stop it, but because I wasn't able to select the atbswp window, F9 did nothing.  Had to reboot to get out of it.

Afterward I confirmed that both the recording hotkey and the playback hotkey exhibit this behavior.

**Comment by RMPR** [comment]
Yeah you're right, this issue's being tracked here #10, didn't find the
time to really wrap my head around this. But you don't have to reboot
your computer to make the playback stop, it's kinda extreme imho. Just
launch atbswp from the terminal and close the window or use ctrl+c to
stop it (I use the version from source instead of the release). Thanks
for reporting.

**Comment by bmn001** [comment]
The problem is the mouse keeps moving and clicking things, so I'm not able to give focus to the terminal window to control+c or the atbswp GUI.  No matter how fast I type or move the mouse, the recorded macro keeps one step ahead of me :)  Anyway, glad to know you're already working on it.  Thank you!

**Comment by RMPR** [comment]
I'll close this since it's already tracked elsewhere.
