### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by CryptoXSS** [RMPR/atbswp#90]
how did i pause the recording i tried with fn or fin+f2 and nothing

**Comment by qkum** [comment]
pause? there is no pause

clikc the `settings button`? maybe your answer is there?

A) i would save 2 recordings as .txt files and manually copy-paste file 1 into file 2, add a pause in between if you want with time.sleep() -  (you stopped & saved the recording instead of pausing)
B) i would make 2 recordings and "run" file 1, sleep the main script aka pause, and then run file 2.

- in the future tell us what you are trying to do bro

**Comment by RMPR** [comment]
Thanks for triaging @qkum, have a look at my comments [here](https://github.com/RMPR/atbswp/issues/91#issuecomment-1376087314) if you haven't already. @CryptoXSS I am now closing this issue, feel free to reopen if you have some more questions.
